name=input("Enter Student name: ")
ID=int(input("Enter Student ID: "))
branch=input("Enter Student Branch: ")
math=int(input("Enter Maths marks: "))
chem=int(input("Enter chem marks: "))
phy=int(input("Enter phy marks: "))
CS=int(input("Enter CS marks: "))
English=int(input("Enter English marks: "))
total=math+chem+phy+CS+English
per=(total/500)*100
adm=101
print()
print()
print()
print()
print(21*' ',end=' ')
print("GLA UNIVERSITY,Mathura")
print(18*' ',end=' ')
print(28*'.')
print(15*' ',end=' ')
print("Student information and marksheet")
print(12*' ',end=' ')
print(39*'.')
print()
print(8*' ',end=' ')
print("Student : ",name ,end=8*' ')
print("Student ID: ",ID)
print(8*' ',end=' ')
print("Student Branch: ",branch,end=8*' ')
print("Student add.no: ",adm)
print()
print()
print(22*' ',end=' ')
print("Student Marksheet")
print()
print(10*' ',end=' ')
print("Subjects",end=' ')
print(4*' ',end=' ')
print("Total Marks",end=' ')
print(4*' ',end=' ')
print("Marks obtained")


print(12*' ',end=' ')
print("Math",end=' ')
print(10*' ',end=' ')
print("100",end=' ')
print(14*' ',end=' ')
print(math)

print(12*' ',end=' ')
print("Chem",end=' ')
print(10*' ',end=' ')
print("100",end=' ')
print(14*' ',end=' ')
print(chem)

print(12*' ',end=' ')
print("Phy",end=' ')
print(11*' ',end=' ')
print("100",end=' ')
print(14*' ',end=' ')
print(phy)

print(12*' ',end=' ')
print("CS",end=' ')
print(12*' ',end=' ')
print("100",end=' ')
print(14*' ',end=' ')
print(CS)

print(12*' ',end=' ')
print("English",end=' ')
print(7*' ',end=' ')
print("100",end=' ')
print(14*' ',end=' ')
print(English)

print()
print()
print(10*' ',end=' ')
print("Total: ",total,end=8*' ')
print("Percentage: ",per)
print()
if (math>35 or chem>35 or phy>35 or CS>35 or English>35):
	print(10*' ',end=' ')
	print(14*'.',end=' ')
	print("RESULT : PASS",end=' ')
	print(14*'.',end=' ')
else:
	print(10*' ',end=' ')
	print(14*'.',end=' ')
	print("RESULT : FAIL",end=' ')
	print(14*'.',end=' ')		

